### ISSUE TITLE
Баг

### ISSUE THREAD

**Issue by aidarishkulov** [ssilver2007/ESP8266_LCD_1602_RUS#1]
Проверил:
 
С этими строками:

#ifdef FDB_LIQUID_CRYSTAL_I2C_H
#if defined (ESP8266)
void init(uint8_t _sda = SDA, uint8_t _scl = SCL)
{
Wire.pins(_sda, _scl);
begin();
}
#else
void init()
{
begin();
}
#endif
#else
#if defined (ESP8266)
void init(uint8_t _sda = SDA, uint8_t _scl = SCL)
{
Wire.pins(_sda, _scl);
init();
}
#endif
#endif*/

ЕСП периодически перезагружается (на https://github.com/johnrickman/LiquidCrystal_I2C) , если убрать эти строки, то нормально.

Хватает только этого:

#ifdef FDB_LIQUID_CRYSTAL_I2C_H
void init()
{
begin();
}
#endif

Тогда работает с ЕСП8266 нормально.
Проверял с библиотеками:
1. https://github.com/johnrickman/LiquidCrystal_I2C
2. https://github.com/fdebrabander/Arduino-LiquidCrystal-I2C-library

**Comment by ssilver2007** [comment]
Здравствуйте!
#if defined (ESP8266) - идентификатор определяет, что используется какая-то
из версий ESP8266. Можно ли определить, что точно используется ESP8266-01 ?
Потому, что на этой версии другие пины определяют SDA и SCL.

пт, 18 дек. 2020 г. в 10:27, aidarishkulov <notifications@github.com>:

**Comment by ssilver2007** [comment]
Сделал так:

#ifdef FDB_LIQUID_CRYSTAL_I2C_H
  #if defined(ARDUINO_ESP8266_ESP01)
    void init(uint8_t _sda = SDA, uint8_t _scl = SCL)
    {
      Wire.pins(_sda, _scl);
      begin();
    }
  #else
    void init()
    {
      begin();
    }
  #endif
#elif defined(ARDUINO_ESP8266_ESP01)  //ESP8266-01
  void init(uint8_t _sda = SDA, uint8_t _scl = SCL)
  {
    Wire.pins(_sda, _scl);
    init();
  }
#endif
